pipeline {
    agent any

     tools {
             jdk 'JDK21'
              maven 'Maven3'
           }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }



        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}